### 회원 목록 조회: GET /users
GET http://localhost:8080/mapping/users

### 회원 등록: POST /users
POST http://localhost:8080/mapping/users

### 회원 조회: GET /users/{userId}
GET http://localhost:8080/mapping/users/2

### 회원수정: PATCH /users/{userId}
PATCH http://localhost:8080/mapping/users/3

### 회원 삭제: DELETE /users/{userId}
DELETE http://localhost:8080/mapping/users/4